[project]
name = "journal-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mainak Das", email = "mainakdas104@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
journal-fastapi = "journal_fastapi:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
