"""add journal tables

Revision ID: 4a2561930ca7
Revises: 80f46995ae27
Create Date: 2026-09-15 23:42:46.379115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a2561930ca7'
down_revision: Union[str, Sequence[str], None] = '80f46995ae27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Journal',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('trash', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('Journal_userId_trash_updatedAt_idx', 'Journal', ['userId', 'trash', 'updatedAt'], unique=False)
    op.create_table('Tag',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('Tag_userId_name_idx', 'Tag', ['userId', 'name'], unique=False)
    op.create_index('Tag_userId_name_key', 'Tag', ['userId', 'name'], unique=True)
    op.create_table('Note',
    sa.Column('journalId', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plainText', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('searchVector', postgresql.TSVECTOR(), sa.Computed('\n            setweight(\n                to_tsvector(\n                    \'english\'::regconfig,\n                    coalesce(title, \'\')\n                ),\n                \'A\'\n            )\n            ||\n            setweight(\n                to_tsvector(\n                    \'english\'::regconfig,\n                    coalesce("plainText", \'\')\n                ),\n                \'B\'\n            )\n            ', persisted=True), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['journalId'], ['Journal.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('Note_journalId_createdAt_idx', 'Note', ['journalId', 'createdAt'], unique=False)
    op.create_index('Note_searchVector_idx', 'Note', ['searchVector'], unique=False, postgresql_using='gin')
    op.create_table('NoteShare',
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('noteId', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['noteId'], ['Note.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('noteId'),
    sa.UniqueConstraint('token')
    )
    op.create_table('_NoteToTag',
    sa.Column('A', sa.Text(), nullable=False),
    sa.Column('B', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['A'], ['Note.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['B'], ['Tag.id'], onupdate='CASCADE', ondelete='CASCADE')
    )
    op.create_index('_NoteToTag_AB_unique', '_NoteToTag', ['A', 'B'], unique=True)
    op.create_index('_NoteToTag_B_index', '_NoteToTag', ['B'], unique=False)
    op.drop_table('test-model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test-model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('test-model_pkey'))
    )
    op.drop_index('_NoteToTag_B_index', table_name='_NoteToTag')
    op.drop_index('_NoteToTag_AB_unique', table_name='_NoteToTag')
    op.drop_table('_NoteToTag')
    op.drop_table('NoteShare')
    op.drop_index('Note_searchVector_idx', table_name='Note', postgresql_using='gin')
    op.drop_index('Note_journalId_createdAt_idx', table_name='Note')
    op.drop_table('Note')
    op.drop_index('Tag_userId_name_key', table_name='Tag')
    op.drop_index('Tag_userId_name_idx', table_name='Tag')
    op.drop_table('Tag')
    op.drop_index('Journal_userId_trash_updatedAt_idx', table_name='Journal')
    op.drop_table('Journal')
    # ### end Alembic commands ###
